# Generated by Django 5.2.7 on 2025-10-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Taom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=50)),
                ('tavsifi', models.TextField()),
                ('narxi', models.IntegerField()),
                ('mavjudligi', models.BooleanField()),
                ('kategoriyasi', models.CharField(choices=[('salat', 'Salat'), ('asasiy', 'Asasiy taollar'), ('shirinliklar', 'Shirinliklar')])),
                ('rasm', models.ImageField(upload_to='')),
            ],
        ),
    ]
