# Generated by Django 5.2.7 on 2025-10-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taom',
            name='rasm',
        ),
        migrations.AddField(
            model_name='taom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='taom',
            name='kategoriyasi',
            field=models.CharField(choices=[('Salatlar', 'Salatlar'), ('Asosiy taomlar', 'Asosiy taomlar'), ('Shirinliklar', 'Shirinliklar'), ('Ichimliklar', 'Ichimliklar')]),
        ),
        migrations.AlterField(
            model_name='taom',
            name='mavjudligi',
            field=models.CharField(choices=[('Ha', 'Ha'), ('Yoq', 'Yoq')], default='Ha'),
        ),
        migrations.AlterField(
            model_name='taom',
            name='narxi',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
